/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.6/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "xq-sdk-jvm"

pluginManagement {
    repositories.gradlePluginPortal()
    includeBuild("plugins")
}

include("app")
include("business-logic")
include("data-model")

dependencyResolutionManagement {
    repositories.mavenCentral()
}
